name: MaosAmigas
values:
  - key: host
    value: ''
  - key: client-id
    value: ''
  - key: client-secret
    value: ''
  - key: username
    value: ''
  - key: password
    value: ''
  - key: token
    value: ''
