services:

  postgres:
    image: postgres:17
    container_name: maos-amigas-postgres

    environment:
      POSTGRES_DB: MaosAmigas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"

    ports:
      - "5434:5434"

    volumes:
      - maos_amigas_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MaosAmigas"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: maos-amigas-api

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5434/MaosAmigas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"

      CLIENT_ID: myclientid
      CLIENT_SECRET: myclientsecret
      JWT_DURATION: 86400

      CORS_ORIGINS: http://localhost:3000,http://localhost:5173

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  maos_amigas_postgres_data: